services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/rails_book/intro
    tty: true
    stdin_open: true
    command: bash # コンテナ内でbashを起動。Railsサーバーは手動で起動